### ISSUE TITLE
create large ascii text translator

### ISSUE THREAD

**Issue by bicknrown** [makeopensource/dotdot#2]
**Is your feature request related to a problem? Please describe.**
a way to take input text and output large ascii art like text to print

**Describe the solution you'd like**
as described above, the solution should be scalable to a wide variety of sizes depending on printer paper size.

**Describe alternatives you've considered**
there are many ways to do this, especially with the constraints of the printer. 

**Additional context**
ask on this issue if you need clarification.

**Comment by emilkovacev** [comment]
[https://pypi.org/project/text-to-font/](This) package should be enough to satisfy the constraints of this issue, is there any additional properties that this should have?
